### ISSUE TITLE
FE-BEの動作モードの連動

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/barebone-studio#116]
- 課題
  - optinist の動作モードは現在2つあるが（standalone, multiuser）、FEとBEで動作モードの設定が連動していない。（別々に設定必要）
  - 上記のため、設定が不一致する可能性があるが、現状では設定不一致となった場合、要因が判別しづらくなっている。（ログの不足等）

- 対策
  - FEとBEの動作モードの設定個所を一元化する
    - ※具体的な方式は、検証から
  - 動作モードの不一致があった場合のエラー処理を明確にする（API error応答, ログ出力）

**Comment by hunghongnam** [comment]
Liết kết mode hoạt động của FE-BE

1/ Issue.

Hiện tại có hai mode hoạt động của optinist（standalone, multiuser）, nhưng chưa  set liên kết mode hoạt động  cho FE và BE (cần cài đặt riêng)
Vì lý do trên nên có khả năng cài đặt không khớp nhau,  hiện tại khi xảy ra cài đặt không khớp đó thì rất khó xác định nguyên nhân. (thiếu log, v.v.)

2/ Giải pháp

- Tập trung nơi cài đặt mode hoạt động FE và BE
  *Phương pháp cụ thể sẽ được xác định sau khi xác minh.
- Làm rõ việc xử lý lỗi khi có sự không khớp nhau trong mode hoạt động (API error, xuất nhật ký)
