### ISSUE TITLE
Docs - code sections do not have copy button

### ISSUE THREAD

**Issue by milesOIST** [arayabrain/barebone-studio#142]
Copy button is convenient for users

**Comment by ReiHashimoto** [comment]
@milesOIST 
Could you explain details?

- What is `code sections`?

**Comment by milesOIST** [comment]
<img width="759" alt="image" src="https://github.com/arayabrain/barebone-studio/assets/34530789/e7d599f5-b04a-4880-b24c-680d6644bfc4">

**Comment by milesOIST** [comment]
https://sphinx-copybutton.readthedocs.io/en/latest/index.html

**Comment by ReiHashimoto** [comment]
@milesOIST 
I get it. Looks fine!
Pls implement it.
