### ISSUE TITLE
[136] Overflow Error in CaImAn with huge input data.

### ISSUE THREAD

**Issue by ReiHashimoto** [arayabrain/barebone-studio#164]
## 概要
容量が大きいデータを使用してcaiman_mc→caiman_cnmfを実行した際に、以下のようなエラーで失敗する。
- サンプルデータ
  - https://drive.google.com/file/d/1fiEpDIO0T5kJMm8m6aw4IgCIBJTRLEgw/view?usp=drive_link
- エラーログ
    ```
    OverflowError: serializing a bytes object larger than 4 GiB requires pickle protocol
    4 or higher
    ```
    - dataclassのsave_jsonメソッド内、`np.save`を実行した時に発生している

上記以外にも、以下のエラーが出る場合もある

```
 in _error_on_new_warn_on_construct raise ValueError(error_msg) ValueError: ImageSeries 'corrected': Format must be 'external' when external_file is specified.
```

```
2023-07-07 17:07:48,782 : ERROR - logger.py - {'level': 'debug', 'msg': 'Full Traceback (most recent call last):
File "/Users/rei_hashimoto/anaconda3/envs/test/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2577, in run_wrapper
  run(
File "/Users/rei_hashimoto/anaconda3/envs/test/lib/python3.8/site-packages/optinist/Snakefile", line 94, in __rule_4
File "/Users/rei_hashimoto/anaconda3/envs/test/lib/python3.8/site-packages/snakemake/script.py", line 1567, in script
  executor.evaluate()
File "/Users/rei_hashimoto/anaconda3/envs/test/lib/python3.8/site-packages/snakemake/script.py", line 462, in evaluate
  self.execute_script(fd.name, edit=edit)
File "/Users/rei_hashimoto/anaconda3/envs/test/lib/python3.8/site-packages/snakemake/script.py", line 683, in execute_script
  self._execute_cmd(
File "/Users/rei_hashimoto/anaconda3/envs/test/lib/python3.8/site-packages/snakemake/script.py", line 493, in _execute_cmd
  return shell(
File "/Users/rei_hashimoto/anaconda3/envs/test/lib/python3.8/site-packages/snakemake/shell.py", line 300, in __new__
  raise sp.CalledProcessError(retcode, cmd)\nsubprocess.CalledProcessError: Command \'source /Users/rei_hashimoto/anaconda3/bin/activate \'/Users/rei_hashimoto/anaconda3/envs/test/lib/python3.8/site-packages/.snakemake/conda/3abd0cc9bc7ca3d1a0991ab5273621c1_\'; set -euo pipefail;  python /Users/rei_hashimoto/anaconda3/envs/test/lib/python3.8/site-packages/.snakemake/scripts/tmp_0noz5l5.func.py\' returned non-zero exit status 137.\n', 'timestamp': 1688717268.780235}
```

## 対応方法
対応方針要調査。

- numpy.saveから呼び出されるpickle.dump(array, fp, protocol=3, **pickle_kwargs)で、protocolを4以上にする必要がある
  - numpy.saveではパラメータを編集できないようなので、同等のメソッドを作成？

**Comment by ReiHashimoto** [comment]
まずは再現性、および原因について調査を行う。

**Comment by quanpython** [comment]
- Of course, it's possible to create an equivalent method to `np.save`. 
	But I think using method `save_json`(the function uses `np.save`) in LccdData, Suite2pData, CaimanData class is no longer necessary, because they are already saved in the pickle file of the workflow node dirpath. https://github.com/arayabrain/barebone-studio/blob/b44bea0bf16e0a950b2923473d1926e2fd3bdce5/studio/app/common/core/rules/runner.py#L60
	In #107 , I removed these processes.

> ImageSeries 'corrected': Format must be 'external' when external_file is specified.

I have not been able to reproduce this error.

> ...snakemake/scripts/tmp_0noz5l5.func.py\' returned non-zero exit status 137

Exit code 137 occurs when a process is terminated because it’s using too much memory. A server with more powerful RAM and CPU can limit this error.

**Comment by ReiHashimoto** [comment]
- #107 の実装により、OverflowErrorは解消され、caiman_mcまでは実行できることを確認
- ただし、caiman_cnmfはメモリ不足で`returned non-zero exit status 137`のエラー、またはPython Backendが応答しない状態になってしまった
  - 実行環境
    - MacOS 14.2 (23C64)
    - memory 16GB
    - Chip Apple M2
- 32GB以上のメモリ環境での検証結果次第でcloseしたい

**Comment by ReiHashimoto** [comment]
https://caiman.readthedocs.io/en/latest/On_file_types_and_sizes.html

- 4GB以上の単一ファイルはCaImAnとしても非推奨のため、OptiNiSt側でファイルを分割するような処理を設ける？

**Comment by ReiHashimoto** [comment]
## ToDo
ImageDataにファイル分割の機能を設ける。
### Details
ImageDataのコンストラクタで`isinstance(data, str)`の条件にマッチする場合、入力ファイル（self.pathにあるファイル）のデータサイズチェックを行う。
2GBを超える場合、以下の処理を行う。
- tiffファイルを一つのファイルサイズが2GB以下になるようにtimeの軸で分割する
  - 分割のロジックはおそらく以下のような2パターンあると思いますが、実装しやすい方法でOKです(Bの方がやりやすいかもしれません)
    - 例えば7GBのファイルの場合
      - (A) 2GBのファイル3つと1GBのファイル1つに分ける
      - (B) 1.75GBのファイル4つに分ける
- 分割したファイルは`{output_dir}/tiff/{分割前のファイル名}/{分割前のファイル名}_{連番}.tiff`に保存
  - 例) {output_dir}/tiff/sample_file/sample_file_2.tiff
- self.pathは分割後のファイルのリストにする

この実装の確認にあたり、以下の条件での動作に問題がないことを確認してください。
- 条件
  - 入力ファイル：`sample_data/input/sample_mouse2p_image.tiff`
  - 上記データは66.5MBのため、ファイル分割の閾値を2GB→30MBに変更
  - 以下の2つのワークフローを実行
    - Image→suite2p_file_convert→suite2p_registration→suite2p_roi
    - Image→caiman_mc→caiman_cnmf
- 期待される結果
  - `{output_dir}/tiff/sample_mouse2p_image/sample_mouse2p_image_{n}.tiff`ファイル3つが生成されていること
  - suite2p, caimanの実行結果（VISUALIZE）で確認が当実装前と変わらないこと
