### ISSUE TITLE
[105] NWBファイルの入力からROI、fluorescenceを再現する

### ISSUE THREAD

**Issue by ReiHashimoto** [arayabrain/barebone-studio#167]
## 実装パターン1：0.8
- 現在のHDF5ノードでSTRUCTUREを探索した際に、dataなどのディレクトリではない要素に対して、「View as」アイコンを設ける
- アイコンクリック後、データ形式をリストから選択(ImageData, RoiData, FluoData)するポップアップが表示される
- ポップアップからデータ形式を選択後、対象のデータ型を表示するVisualizeパネルが表示される

### メリット
- HDF5ノードのみで操作が完結する

### デメリット
- 想定工数が多い

## 実装パターン2：0.2
- 専用のアルゴリズムノードを設ける。
- HDF5ノードで対象の配列を選択したものを入力として、上記アルゴリズムを含むワークフローを実行することで、outputとして表示可能となる

### メリット
- VISUALIZEパネルを利用できるため、複数のアウトプットを同時に確認可能
- 既存機能を活用するため、比較的工数が少ない

### デメリット
- RUNの操作を挟む
- 表示対象の配列ごとに入力・出力のワークフローを用意する必要がある

## 備考
- RoiDataについては、NWBファイルに保存されているデータのみでは不足しているため、 #166 の際に対象のデータも含めてRoiDataに保存できるように対応する。

**Comment by hunghongnam** [comment]
Tái hiện ROI、fluorescence từ input file NWB

Implement patern 1 : 0,8
- khi tìm kiếm STRUCTURE trong node HDF5 hiện tại, set icon「View as」 cho các thành phần không phải là directory, chẳng hạn như data.v.v.
- Sau khi click icon, hiển thị dialog để chọn định dạng dữ liệu từ list (ImageData, RoiData, FluoData).
- Sau khi chọn định dạng dữ liệu từ popup, panel Visualize hiển thị loại dữ liệu đích sẽ được hiển thị.

Ưu điểm:
Kết thúc thao tác chỉ với node HDF5

Nhược điểm:
Công số lớn

Implement patern 1 : 0,2
- Set node algorithm chuyên dụng.
- Bằng cách input mảng đối tượng được chọn trong node HDF5,run workflow bao gồm algorithm trên, thì nó có thể được hiển thị ra ở outpupt.

Ưu điểm:
- Vì có thể sử dụng Panel VISUALIZE nên có thể kiểm tra nhiều output cùng lúc
- Vì nó sử dụng các chức năng hiện có nên tốn ít công số

Nhược điểm:
- Chèn thao tác RUN
- Cần chuẩn bị workflow input/output cho từng mảng sẽ được hiển thị.

Bổ sung:
Về RoiData, do dữ liệu được lưu trữ trong tệp NWB là không đủ, nên sẽ đối ứng để có thể lưu data đối tượng  vào RoiData khi  [112] OptiNiStでのNWBスキーマ仕様策定 #166
