### ISSUE TITLE
[108] Matlab(.mat)形式のmatrixデータを入力可能にする

### ISSUE THREAD

**Issue by ReiHashimoto** [arayabrain/barebone-studio#168]
## 仕様案
- matlab input ノードを設ける
- 拡張子は.matを受け入れ可能とする
- 上記ノードにはHDF5ノードのような形式で、ネストしたフィールドの探索を行う仕様とする
  - フィールド探索の際に、データに相当する部分では、配列の場合shapeを表示する
- 対象のデータ部分を選択することで、そのデータをImageData AnyTypeとして利用可能にする
　- コネクタ部分はHDF5のように黒

**Comment by ReiHashimoto** [comment]
UIとしては、matlabやjupyter notebookの変数ビューアに近いテンプレートなどがあればそれを使用

**Comment by hunghongnam** [comment]
Cho phép nhập dữ liệu matrix ở định dạng Matlab (.mat) 

Spec ( đề án )
- Tạo node matlab input 
- Cho phép chấp nhận phần đuôi .mat
- Node trên có định dạng tương tự như node HDF5 và được thiết kế để tìm kiếm các trường đã nest.
   Khi search field, ở phần tương ứng dữ liệu sẽ hiển thị shape trong trường hợp là mảng.
- Tạo viewer data như node  csv
  Đối ứng với cả transpose mảng
  Vì dữ liệu mảng 3 chiều được giả định nên cần hỗ trợ hiển thị slice
- Bằng cách chọn phần dữ liệu đối tượng , cho phép có thể sử dụng dữ liệu đó dưới dạng ImageData AnyType
  Phần connector có màu đen như HDF5

**Comment by hunghongnam** [comment]
Sử dụng dữ liệu mảng như hình ảnh trong tệp định dạng .mat làm input phân tích.
Trong tệp định dạng .mat, dữ liệu đích có thể được truy cập bằng cách chỉ định tên trường, do đó trường dữ liệu đích có thể được chọn trên node GUI.
Nếu dữ liệu đích ở định dạng Matlab Struct thì cũng có thể tìm kiếm bên trong đó.

Trong số các node hiện tại thì nó gần giống vơi node  HDF5

Khi tải data sample bên dưới, dự kiến ​​sẽ có những điều sau đây.
(check 2 hình ảnh trên )

Sample data đã kéo về drive :
https://drive.google.com/drive/u/0/folders/1E5zyX2O8oCEkdi0OJDypjjHa8Pgn9zvX
-------------------------------

BE:
Implement API parse đơn giản cho dữ liệu Matlab
- Implement API tìm kiếm đệ quy tên trường và trường Matlab Struct trong tệp .mat tại đường dẫn đã chỉ định và trả về ở định dạng dict.
- Giao diện dữ liệu cũng tương tự như HDFNode, các bạn tham khảo nó.
- Khi parse các tệp .mat, hãy sử dụng Loadmat của scipy.io, v.v.
- Nếu bạn tìm kiếm và tiếp cận dữ liệu khác ngoài Matlab Struct,thì có thể hiển thị chuỗi sau trên FE.
  - mảng
     Định dạng FIELD_NAME (shape=(SHAPE)) như trên
  - Ngoài mảng
  Hiển thị FIELD_NAME (TYPE)

Xử lý dữ liệu khi run Workflow
- Điều này cũng implement dựa trên việc implement các node HDF5.
  - Nhận tên tệp và đường dẫn đến trường bằng API và trích xuất dữ liệu
  - Nếu dữ liệu là 2 chiều thì nó được coi là TimeSeriesData và nếu là 3 chiều thì nó được coi là ImageData.

FE
Implement node dữ liệu cho Matlab
- Tạo một node input chuyên dụng (matlab)
  - Vì định dạng dữ liệu không được xác định nên handle color của node là màu đen (giống như HDF5)
- Cấu trúc gần giống như HDF5.
  - Khi tải file thì btn ”STRUCTURE” sẽ được hiển thị.
    - Khi click vào btn ”STRUCTURE” thì sẽ hiển thị dialog, và cấu trúc file sẽ đươc hiển thị  . Cấu trúc được lấy từ BE bằng API.
    - Người dùng có thể chọn dữ liệu từ cấu trúc tệp được hiển thị.

**Comment by ReiHashimoto** [comment]
Apologies, re-considering #171 , I want to update the layout for structure preview like this.
(Following image is for illustrative purpose only.)

![Screenshot 2023-12-21 at 15 59 50](https://github.com/arayabrain/barebone-studio/assets/42664619/4dfc0779-ca30-49a5-85b1-de324506aa93)

- Show field names, types and shapes with separated columns. And add header line for columns.
- If data is array, show "array" for type.
