### ISSUE TITLE
[101] tiff fileの形式チェック

### ISSUE THREAD

**Issue by ReiHashimoto** [arayabrain/barebone-studio#171]
ImageNodeに対し、

- アップロードされたtiffファイルのshapeの表示を追加する
- そもそも配列として認識できない場合は警告メッセージを出す

**Comment by ReiHashimoto** [comment]
画面のイメージ


![Image](https://github.com/arayabrain/barebone-studio/assets/42664619/358b8d15-9e1b-43ca-b629-0fee49d7c7d6)


- (tiffファイルで発生するか分かりませんが) 万が一shapeが取得できないデータの場合
  - shape欄にerror icon(https://mui.com/material-ui/material-icons/?query=error&selected=ErrorOutline)をcolor "error"表示
  - アイコンにhoverした際に"parsing image shape failed"のメッセージがtooltipで表示されるようにする

image dataのshape取得を毎回実行すると処理が重くなることが想定される
- OPTINIST_DIRのinputディレクトリに、shape情報を記録するファイルを作成する
  - jsonなどがそのままレスポンスに使えるのでreturnの際に扱いやすい?
  - できればファイル名の先頭に`.`を入れるなどして、隠しファイルにする
- ファイル内、またはファイル名にtimestampを記録する
  - そのtimestampとディレクトリ内のファイルの最終更新時刻を比較して、差分更新されるようにする
処理を軽くするための設計についてはあくまで案なので、より良い方法があれば提案していただきたい

**Comment by ReiHashimoto** [comment]
- OSのファイル修正時刻が取得できないため、timestampは保持しない
- 代わりに、単体のファイルに対してshape情報再取得のエンドポイントを設ける
  - GUIのファイル選択画面でshape情報の右に更新ボタンを設け、単体のshape情報再取得を実行可能にする

**Comment by hunghongnam** [comment]
1/ Với ImageNode,
- Add hiển thị shape của file tiff được upload
- Đưa ra message cảnh báo nếu không nhận biết được đó là mảng

2/ Image màn hình ( check ảnh trên )

- Nếu trường hợp data không thể get shape ( do file tiff hay không thì ko biết ) 
  - Hiển thị icon "error" error icon(https://mui.com/material-ui/material-icons/?query=error&selected=ErrorOutline)ở cột shape
  - Khi hover vào icon thì hiển thị message sau ở tooltip : "parsing image shape failed"

Nếu mọi lần đều run get shape của imagedata thì xử lý sẽ nặng nên:

- Tạo file để ghi thông tin shape vào thư mục input của OPTINIST_DIR
  - json, v.v. có thể được sử dụng vào response nên dễ xử lý khi return ? 
  - Nếu có thể thì thêm . ở đầu file name để ẩn file
- Ghi timestamp vào file name hoặc trong file
   - So sánh timestamp đó với thời gian update lần cuối file trong thư mục đó, rồi thực hiện update sự thay đổi.

=> Vì Không thể get được thời gian sửa file trong OS nên không lưu timestamp nưa.
Thay vào đó sẽ chuẩn bị endpoint để get lại thông tin shape với các file đơn lẻ.
=> Thêm btn update ở bên phải cột share ở màn hình chọn file trên GUI, và cho phép run get lại thông tin shape đơn lẻ.
