### ISSUE TITLE
[103] URLリンクからのデータアップロード

### ISSUE THREAD

**Issue by ReiHashimoto** [arayabrain/barebone-studio#173]
## 概要
- ノードのファイルアップロードで、URL経由でファイルをアップロードする機能を追加する

### Data nodeのデザイン改修

ボタンが増えてレイアウトが崩れるため、各データノードのデザインを改修する
<img width="610" alt="Screenshot 2023-11-29 at 19 32 21" src="https://github.com/arayabrain/barebone-studio/assets/42664619/939205cf-334e-464d-9160-e086b545334a">

- ノードの種類(image, csvなど、左のパネルのデータノードの名称でよい)を上に表示するようにする
- 各ボタンをアイコンボタン形式にする
- それぞれのボタンはTooltipでtitleを表示する
  - Select from uploaded files → 現在の"Select XXX"ボタンの機能
  - Upload file → 現在の"LOAD"ボタンの機能
  - Upload file via URL → 機能を新規追加(後述)
  - また、CSVをアップロードできるノード（csv, fluo, behavior）は、ファイル選択後に"SETTINGS"ボタンが表示されるが、これもSettings iconとして上記のボタンの右側に表示されるようにする

### URL経由でのファイルアップロード機能
- Upload file via URLのIconButtonをクリックするとダイアログが表示される
  - ダイアログにはテキストフィールドでURLの入力欄を設ける
  - テキストフィールドはURLのバリデーションを入れる
    - http(s)://で始まり、ノードが受け入れ可能な拡張子で終わるURLであること
      - GoogleDriveのようにURLから直接ファイル取得できないリンクについては対象外で良い
  - DialogActionsは”CANCEL”, "LOAD"
    - "LOAD"はバリデーションOKな場合のみ活性化する
- BackendでGET `/files/{workspace_id}/download/{url}`のエンドポイントを設ける。
  - urlから対象のworkspace_idのinput directoryにファイルダウンロードを行う
  - ダウンロードに時間がかかることが想定されるため、background taskなどでダウンロードを実行
  - ダウンロードのstatusを定期的にポーリングして取得できるようにエンドポイントを設ける
  - ダウンロードが完了したら、"File upload finished!"のsuccess snackbarで通知を行い、selected fileをダウンロードしたファイルにする

## 検討事項
- [ ] 複数ファイルの同時ダウンロードは必要ないか？
  - 1ファイルごとのダウンロードで進める

**Comment by hunghongnam** [comment]
Upload data từ  link URL

Sơ lược:
Add thêm chức năng upload file thông qua URL bằng node upload file

Spec:
Sửa design của Data node
Có nhiều btn hơn nên sẽ bị vỡ layout nên cần sửa design các data node.

- Hiển thị loại node ở trên cùng.(image, csv, v.v., có thể là tên của data node ở bảng panel bên trái là dc) 
- Cho các btn thành định dạng icon btn 
- Mỗi btn đều hiển thị title với tooltip
 Select from uploaded files  → Chức năng btn "Select XXX" hiện tại
 Upload file  → Chức năng btn "LOAD" hiện tại
 Upload file via URL → Thêm chức năng mới (sẽ mô tả sau)
 Ngoài ra, đối với các node có thể upload CSV (csv, fluo, Behavior), btn "SETTINGS" sẽ được hiển thị sau khi chọn file, nhưng btn này cũng sẽ được hiển thị dưới dạng Settings icon ở bên phải nút trên.
