### ISSUE TITLE
[111] AllenSDKを使用するJupyter notebookの作成

### ISSUE THREAD

**Issue by ReiHashimoto** [arayabrain/barebone-studio#174]
以下の処理を含むjupyter notebookを作成する

- OptiNiStで作成したNWBファイルをpython, matlabで読み込む(pyNWBなどでOK)
- 読み込んだデータを使用してAllen SDKでの解析を行う

**Comment by itutu-tienday** [comment]
Memo)

> OptiNiStで作成したNWBファイルをpython, matlabで読み込む(pyNWBなどでOK)
上記は、準備可能

> 読み込んだデータを使用してAllen SDKでの解析を行う
上記は、v1.2.0 でのNWB整理結果は、Allen SDKに対応する形とは最終的にならなかったことから、対応対象外となっている
