### ISSUE TITLE
ROI Edit機能テスト（再）

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/barebone-studio#229]
ROI Edit機能追加 (#535) の再テスト

- 最新設計ドキュメント
  - https://drive.google.com/drive/folders/12vCERJca_IuJ1dipvZni-SaeSaWBJieD
    - 535 [No.15]ROI Edit モード機能の追加_v3.pptx
      - v1 時点から P.2,3 を追加

**Comment by itutu-tienday** [comment]
12/5版のテストレポートについて、数点指摘と質問があります。

- Sheet. 535_Function ROI
  - Cancel edit ROI_xx で 「Edit ROIのデータを保存する確認」とありますが、ここは「Edit ROIの編集途中のデータの破棄を確認」ではないでしょうか。
- Sheet. Matrix_ROI
  - Matrix（W12:AH:20）の ①,② の番号は、何を示していますでしょうか？

**Comment by linhb273** [comment]
> 12/5版のテストレポートについて、数点指摘と質問があります。
> 
> * Sheet. 535_Function ROI
>   
>   * Cancel edit ROI_xx で 「Edit ROIのデータを保存する確認」とありますが、ここは「Edit ROIの編集中データを破棄する確認」ではないでしょうか。
*  その通りです。「Edit ROIのデータを保存する確認」を「Edit ROIの編集中データを破棄する確認」に修正しました。
> * Sheet. Matrix_ROI
>  
>   * Matrix（W12:AH20）の ①,② の番号は、何を示していますでしょうか？
* ①,② の番号はテストケースステップを示しています。
例：テストケース１（W12）：
①ー＞ステップ①：「Select Item」で「.tiff」ファイルを選択するし、「Select Roi」で「all_roi」を選択します。
②ー＞ステップ②：「Select Item」で「all_roi」を選択します。

**Comment by itutu-tienday** [comment]
@linhb273 

> - ①,② の番号はテストケースステップを示しています。
> 例：テストケース１（W12）：
> ①ー＞ステップ①：「Select Item」で「.tiff」ファイルを選択するし、「Select Roi」で「all_roi」を選択します。
> ②ー＞ステップ②：「Select Item」で「all_roi」を選択します。

上記、了解しました。
なお備忘のため、上記について、テストレポート内にも補足追記しておいていただければ思います。

**Comment by linhb273** [comment]
> なお備忘のため、上記について、テストレポート内にも補足追記しておいていただければ思います。

> はい、テストレポート内にも補足追記いたしました。
