### ISSUE TITLE
[104][OLYMPUS]SDK Sample Code Python Porting

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/barebone-studio#244]
OLYMPUS顕微鏡データ対応の Workflow Image Node の作成に先立ち、
OLYMPUS顕微鏡データのSDK（ライブラリ）の仕様把握のため、SDKサンプルコード（C++）のPythonへの移植を実施する。

- リソース
  - SDK・サンプルコード・テストデータ
    - https://drive.google.com/drive/folders/1VjEW6VUQhtdsrmOYLpUzFNdTDhhs_5GR
  - ライブラリファイルのみの格納
    - https://drive.google.com/drive/folders/1wIbYZIimjqjap0Hw_UHJYISZEEvkomgL
  - Documents
    - データ内プロパティ仕様
      - https://drive.google.com/file/d/1XCJRLNFJWfKgkHgebHy0GmDZVjbkHgVC

- 想定成果物
  - サンプルプログラム（IDA_Sample）のPython化コード
    - 想定動作環境は Docker(Ubuntu 22.04, Debian 12 相当 → `python:3.8.18-slim`)
      - Linux版ライブラリ提供までは、Windowsライブラリを利用する
    - DLLを操作するため、ctypes を利用しての実装を想定

- 補足
  - 仕様把握が目的のため、すべてのサンプルプログラムの移植は必須ではない。 （特に問題がなければ、すべて移植想定）

- 関連
  - #198 
  - #202

**Comment by quanpython** [comment]
Source code (Working in progress): https://drive.google.com/file/d/1LIVWgZU9yjgcuV9Gi0B5ncUv4Zsrwfju/view?usp=sharing

**Comment by itutu-tienday** [comment]
SDKサンプルコードのpython移植は対応ボリュームが多いことが確認されたため、直接移植対象プログラムのpython移植を実施する方向で、検討する。

- 関連データ格納パス
  - https://drive.google.com/drive/folders/1PGGh_5YdyRw576KuCJ8vWrizC9ljzYl0

- 移植対象コード
  - read_oir_info.cpp
  - read_oir.cpp
- 備考
  - 上記のコードは旧ライブラリバージョン（2014頃）が利用されているため、最新ライブラリとはInterfaceが変化している。
  - 上記のコードの参照ファイル（,h, .lib など）は 上記フォルダ内の IDA/IDA_Sample3 配下に格納している。 （ファイルをマージしでビルドが可能）

**Comment by hunghongnam** [comment]
[104][OLYMPUS]Convert Python SDK sample code 

Trước khi tạo node Workflow Image Node tương thích với dữ liệu kính hiển vi OLYMPUS,
Để hiểu các thông số kỹ thuật của SDK (thư viện) cho dữ liệu kính hiển vi OLYMPUS, sẽ thực hiện  convert SDK samplecode (C++) sang Python.

- Source:
  - SDK/sample code/test dataa 
https://drive.google.com/drive/folders/1VjEW6VUQhtdsrmOYLpUzFNdTDhhs_5GR
  - Chỉ lưu file thư viện 
https://drive.google.com/drive/folders/1wIbYZIimjqjap0Hw_UHJYISZEEvkomgL

- Sản phẩm giả định

  - Python hóa code của sample program (IDA_Sample)
  - Môi trường hoạt động giả định là Docker (Ubuntu 22.04, tương đương Debian 12 → python:3.8.18-slim)
    *Cho đến khi có thư viện phiên bản Linux, hãy sử dụng thư viện Windows.
  - Giả định là thực hiện bằng cách sử dụng ctypes để vận hành DLL

- Phần bổ sung

 Vì mục đích là để hiểu các thông số kỹ thuật nên không cần thiết phải chuyển tất cả các sample program. (Nếu không có vấn đề gì thì giả định là sẽ convert tất cả)

- Task liên quan

[104][Olympus]ライブラリ・データ検証 #198
[104][OLYMPUS]Workflow Data Node組み込み #202

**Comment by hunghongnam** [comment]
Vì đã xác nhận rằng việc convert pythonSDK sample code có khối lượng lớn nên sẽ xem xét việc convert trực tiếp chương trình sang python.

- Đường dẫn lưu trữ dữ liệu liên quan (đã kéo về drive nội bộ)
https://drive.google.com/drive/u/0/folders/11bL2zaYhRATyZZFxnaKTULCcHoXXbzVd

- code đối tượng convert
 read_oir_info.cpp
 read_oir.cpp

- Note

  - Đoạn code trên sử dụng phiên bản thư viện cũ (khoảng năm 2014) nên Interface đã thay đổi so với thư viện mới nhất.
  - Sample dat được lưu trữ dưới sampledata ở trong thư mục trên. (raw data (.oir) và data kết quả xử lý read_oir*.cpp)
  - Các tệp tham chiếu cho code trên (,h, .lib, v.v.) được lưu trữ trong IDA/IDA_Sample3 trong thư mục trên. (Có thể merge file rồi build)
  - Giả định rằng cuối cùng nó sẽ được tích hợp vào mô-đun sau (được triển khai sau khi convert xong)
https://github.com/arayabrain/barebone-studio/tree/feature/microscope/olympus/studio/app/optinist/microscopes
 OIRReader.py
 test_OIRReader.py

**Comment by tuanna26** [comment]
Here is the source code converted to Python up to now
https://drive.google.com/file/d/1L4pV8d914dihYdEcq37WZLdfJQs0pgna/view?usp=sharing

**Comment by itutu-tienday** [comment]
以下へ、コード移植結果の検証方法 について追記。

- https://github.com/arayabrain/barebone-studio/issues/244#issuecomment-1869342140
> - コード移植結果の検証方法
>   - read_oir_info.cpp
>     - 以下のデータ（メタデータ）を比較する。
>       1. 上で記載の `データ1. ユーザーからの受領データ` の `read_oir_info.cpp の出力データ` (.mat)
>       2. 移植コードの出力データ （1. のデータと内容比較が行えれば良いので、ファイル形式は .mat でなくとも良い（.jsonなどでもOK））
>   - read_oir.cpp
>     - 以下の画像データを比較する（目視比較）
>       1. 元データ（.oir）を Fiji ImageJ などで画像表示
>       2. 取得した画像バイナリデータをtiff形式で保存し、 1. と比較
