### ISSUE TITLE
RUN対象ハイライトの改善

### ISSUE THREAD

**Issue by ReiHashimoto** [arayabrain/barebone-studio#252]
ver1.1.0から、RUN対象のノード(実行済みのワークフローで、パラメータが変更されたノードとそのノードの後ろに連結されているノード)がハイライトされるように機能を改修した。

詳細は以下のドキュメントも参照。
https://optinist.readthedocs.io/en/latest/gui/workflow.html#run

![Screenshot 2023-12-25 at 17 22 14](https://github.com/arayabrain/barebone-studio/assets/42664619/aa9927de-6476-4f2c-a8e1-c563de95bdc8)

- ハイライトの対象は、現状は`AlgrithmNodeType`の`isUpdated`でboolean値で管理している
  - 以下のreducerで`isUpdated`は更新されている
    - `updateParam`
    - `isAnyOf(run.fulfilled, runByCurrentUid.fulfilled)`

上述の通り、現状は"パラメータ変更の操作をしたかどうか"でフラグの管理をしていたが、"パラメータがReproduceした元のワークフローでの値と異なるかどうか"を判定基準とするように修正する。
例)
1. image → suite2p_file_convert → suite2p_registration → suite2p_roiのワークフローをデフォルトパラメータで実行
2. 上記workflowをreproduce
3. Workflow画面で`1Preg`をtrueに変更する（デフォルトのfalseから変更）
    - 現状、ToBe) suite2p_registration, suite2p_roiのノードが黄色にハイライトされる
4. `1Preg`をfalseに変更する
    - 現状）すでに2の操作でisUpdatedがtrueになっており、黄色でハイライトされたまま
    - ToBe) 最初に実行していた時と同じ値のため、2つのノードの黄色のハイライトが解除される
5. 3の後に"RUN"を実行
    - 現状) `forceRunList`にsuite2p_registration, suite2p_roiのデータが含まれる
    - ToBe) `forceRunList`が空の配列になる

## 実装方針
主に以下のような修正を想定。

AlgorithmNodeType.ts
- `AlgrithmNodeType`（Type名にtypoもあるので合わせて修正）
- isUpdated: boolean → originalValue: unknownに変更し、reproduce時点でのparameterの値を格納する

AlgorithmNodeSelectors.ts
- `selectAlgorithmIsUpdated`
  - selectAlgorithmParamsValueの値とoriginalValueの値比較のbooleanに変更

**Comment by hunghongnam** [comment]
Cải tiến highlight đối tượng RUN

Từ phiên bản 1.1.0, chức năng này đã được cải tiến để các node đối tượng RUN được highlight(các node có tham số đã được thay đổi trong workflow đã run và các node được liên kết sau node đó) 

Xem thêm các tài liệu sau để biết chi tiết. (check ảnh)
https://optinist.readthedocs.io/en/latest/gui/workflow.html#run


Đối tượng highlight hiện được quản lý bởi giá trị boolean trong AlgrithmNodeType isUpdated 
 - isUpdated được update trong reducer sau
   - updateParam
   - isAnyOf(run.fulfilled, runByCurrentUid.fulfilled)

Như đã đề cập ở trên, hiện tại đang quản lý flag "đã thực hiên thao tác thay đổi tham số hay không", nhưng sẽ sửa đổi tiêu chuẩn phán định thành  "liệu giá trị tham số có khác với giá trị trong workflow ban đầu đã Reproduce hay không" . 

VD

1. Run workflow sau với param default
 image → suite2p_file_convert → suite2p_registration → suite2p_ro
2. reproduce workflow trên
3. Thay đổi 1Preg thành true trên màn hình Workflow (thay đổi từ default false)
  Hiện tại, các node ToBe) suite2p_registration, suite2p_roi được highlight màu vàng.
4. Thay đổi 1Preg thành false
  - Hiện tại) isUpdated đang thành true theo thao tác mụcc 2 và nó vẫn được highlight màu vàng.
  - Vì giá trị giống với khi run ToBe) lúc đầu, nên highlight màu vàng của node thứ 2 bị xóa 
5. Thực hiện "RUN" sau bước 3
  - Hiện tại) ForceRunList bao gồm dữ liệu suite2p_registration và suite2p_roi
  - ToBe) ForceRunList trở thành một mảng trống

Phương thức implement
Giả định sẽ chủ yếu sửa những nội dung sau:
AlgorithmNodeType.ts

- AlgrithmNodeType (cũng có typo cũng có ở Type name nên các bạn hãy sửa lại cho phù hợp)
- Thay đổi isUpdated: boolean → originalValue: unknown và lưu trữ giá trị parameter tại thời điểm reproduce

AlgorithmNodeSelectors.ts

- selectAlgorithmIsUpdated
 thay đổi thành boolean để so sánh giá trị selectAlgorithmParamsValue và giá trị originalValue
