### ISSUE TITLE
Cannot cancel caiman_mc

### ISSUE THREAD

**Issue by milesAraya** [arayabrain/barebone-studio#353]
**追加機能についての概要**
Caiman_mc takes a long, long time. I thought it might be frozen so i tried to cancel. When I try to cancel, it says 
"Failed to cancel. Please try again". 
Even closing the tab, or ending the session in terminal, and then rerunning, do not help. Opinist just starts running the same workflow automatically

**重要度**
高: この機能を早急に対応しなければ、他の開発に影響を与える。
This may be a major problem for users. 

**ブランチ名**
追加機能のbranchを書く。
Develop-main

**期限**
この機能の完成期限。
None
**ライブラリ**
使用する・使用できそうなライブラリなど。

**その他**
その他コメントなど。
<img width="1512" alt="Screenshot 2024-06-13 at 14 54 47" src="https://github.com/arayabrain/barebone-studio/assets/171535965/497a4af5-fd21-405b-bdac-7aba59915d14">

**Comment by itutu-tienday** [comment]
Note:
The cause was that the version of upload workflow.yaml used for verification was out of date, which caused differences in parameter definitions between yaml and the program, leading to the error.
