### ISSUE TITLE
Create OptiNiSt DFD

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/barebone-studio#370]
- Purpose
  - Understanding optinist specifications (onboarding)
  - Development of optinist design documentation

- Anticipated Deliverables
  - Creation of DFD
  	- Identification of data types referenced by optinist
	- Classification by backend and frontend
	- Visualization of data flow for each function
	  - Workflow(snakemake), API, etc.

- Related
  - #371

**Comment by tsuchiyama-araya** [comment]
現状のDFD


![Image](https://github.com/arayabrain/barebone-studio/assets/169987401/bc633f52-6d3a-4d16-a1f6-4c81301a0c67)

**Comment by itutu-tienday** [comment]
close as document v1 has been released.
