### ISSUE TITLE
frontendのlinter, formatterの追加

### ISSUE THREAD

**Issue by ReiHashimoto** [arayabrain/barebone-studio#42]
backendで導入したflake8, blackのように、frontendにもlinter, formatterおよびpre-commit, GitHub Actionsでのチェックを導入する。

- linter: ESLint
- formatter: Prettier
  - できればimport order用のpluginも追加する(prettier-plugin-organize-importsなど)
- others
  - .vscode/settings.json
  - pre-commit
  - .github/workflows/linters.yml

**Comment by hunghongnam** [comment]
Giống như flake8, black đã đưa vào bằng backend, khách cũng muốn đưa  các tính năng check trong linter, formatter và pre-commit, GitHub Actions ở Frontend 

linter: ESLint
formatter: Prettier
   Nếu có thể, hãy thêm plugin cho import order(chẳng hạn như prettier-plugin-organize-imports)
others
.vscode/settings.json
pre-commit
.github/workflows/linters.yml
