### ISSUE TITLE
[Cloud Support] Setup development environment

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/barebone-studio#422]
### Tasks

- [x] Setup development environment
- [x] Confirm application specs
- [x] Test cases

### Documents

- Environment Setup Procedure
  - https://drive.google.com/file/d/1tJVsgJIaFn-oHSeTgKLSETIaoFmt-BBf/view?usp=drive_link
- Spec Documents
  - https://docs.google.com/presentation/d/1slp8oZSuriSWArkrQKrMnY9SLHw4bOgL/edit?usp=drive_link&ouid=104622411264052056363&rtpof=true&sd=true
  - https://drive.google.com/drive/folders/1l02DPAEBgSkUA9aMggm1ZcwA-oNC82W3
- Testcase
  - https://drive.google.com/drive/folders/1CSBbJlL4vIaWJDoS5IyCWjz6Rv0a-bKO

**Comment by milesAraya** [comment]
Created a S3 bucket and linked it to optinist. Running optinist transferred the files. correctly
<img width="1457" alt="Screenshot 2024-08-29 at 12 28 26" src="https://github.com/user-attachments/assets/91840ebe-21d5-4229-81b8-15559f481eb9">
<img width="720" alt="Screenshot 2024-08-29 at 12 29 18" src="https://github.com/user-attachments/assets/eb50de2e-9882-48e7-a9bc-71a48e10c70d">

**Comment by milesAraya** [comment]
Required steps

1. Create IAM user with CLI access (access key and secret key)
2. Add an S3 bucket
3. Add access key to aws configure
4. Setup multi-user mode optinist. Add to .env file:
     1. REMOTE_STORAGE_TYPE="2"
     2. OFFLINE_STORAGE_DIR="/tmp/optinist/mock-storage"
     3. S3_STORAGE_URL="s3://{MYS3NAME}"
     4. AWS_ACCESS_KEY_ID
     5. AWS_SECRET_ACCESS_KEY

steps 4.4 and 4.5 not in [current walkthrough](https://drive.google.com/file/d/1tJVsgJIaFn-oHSeTgKLSETIaoFmt-BBf/view)

**Comment by milesAraya** [comment]
Issue fixed using boto3 instead of aws cli.[ See here for implementation](https://github.com/arayabrain/barebone-studio/pull/425/commits/9989d615108d9cadf7329e29155ed591feeed065)
