### ISSUE TITLE
Construct AWS mock ECS Enviroment

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/barebone-studio#423]
### Task

Set up AWS ECS and its peripheral services in a basic configuration and understand the basic specifications of each service.

### Composition to be built

Note: Since the objective is to understand the technical specifications, it is not necessary to necessarily reproduce the following configurations.

- Composition
  - ECR
    - First, check using a simple docker image
      - https://hub.docker.com/_/python
  - ECS
	- Fargate
  - RDS ... Ability to connect from Fargate
  - EFS ... Ability to connect from Fargate
  - ALB ...  Can connect to Fargate
  -  Secrets Manager or SM Parameter Store...  Can connect to Fargate
      - https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/developerguide/secrets-app-ssm-paramstore.html
      - https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/developerguide/specifying-sensitive-data.html

- Reference Docs
  - https://docs.google.com/spreadsheets/d/1nROIz8OO49-rer9IA-Q42vL1tUy2WDlo/edit

- Related
  - #422

**Comment by milesAraya** [comment]
I was able to add a dockerfile image to ECR

Dockerfile:
```
# Use an official Python runtime as a parent image
FROM --platform=linux/amd64 python:latest

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install Flask
RUN pip install --no-cache-dir flask

# Make port 5001 available to the world outside this container
EXPOSE 5001

# Run app.py when the container launches
CMD ["python", "app.py"]
```

app.py
```
from flask import Flask

app = Flask(__name__)


@app.route('/')
def hello_world():
    return 'Hello, World!'


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5001)
```

**Comment by milesAraya** [comment]
Created a cluster with fargate and a task with the URI of the ECR image. 
However, the public IP does not work

**Comment by milesAraya** [comment]
Needed to change 
NAT gateway to include 5001 port (specified in the Dockerfile)

<img width="1383" alt="image" src="https://github.com/user-attachments/assets/44aa63e8-8b99-4fd0-bf9d-03d1ebaee1d6">

**Comment by milesAraya** [comment]
ALB setup seems correct

<img width="1101" alt="image" src="https://github.com/user-attachments/assets/48c49852-629c-4d33-a8dc-705d2d7781b3">

<img width="1145" alt="image" src="https://github.com/user-attachments/assets/afef5bc4-fb2f-4e2f-8a48-9750a6ea5406">

**Comment by milesAraya** [comment]
RDS setup and RDS connection tested. 
Tested using script in new task: `yum update -y && yum install -y mysql && echo 'Attempting to connect to RDS' && mysql -h ${DB_HOST} -u ${DB_USER} -p${DB_PASSWORD} -e 'SELECT 1;' && echo 'RDS connection successful' || echo 'RDS connection failed'`

![Image](https://github.com/user-attachments/assets/dc5a6015-aecc-43ed-9bd2-a2c2d7bc5fb4)

**Comment by milesAraya** [comment]
ECR: test1
ECS: researchdx_fargateCluster_ALB_test1
- python_test_service
    - task: python_test1
        - Main task containing python ECR image & flask app. Can check public IP for Hello World page
    - task: RDS-connection-test
        - Run to check RDS connection. Check log to see if connection made. Stops after connection confirmed.
Security groups:

- ALB-security-group
- ECS-Web-Access
- EFS-security-group
- test1-rds-sg
- EFS: test1-EFS (fs-0095aabdb7896d05c)

RDS: database-1
IAM User: ecr_admin
VPC: test1-vpc

**Comment by itutu-tienday** [comment]
@milesAraya 

First a quick check and a few comments.

- No response when accessing the access point?
  - Is the following URL correct?
    - load-balancer-test1-1108326527.ap-northeast-1.elb.amazonaws.com

- Are ECS and EFS connected?  *It looks like there is no connection setting.

**Comment by milesAraya** [comment]
I cannot seem to connect EFS and ECS

```

(optinist_dev) milesd@Miless-MacBook-Pro barebone-studio % aws ecs describe-tasks --cluster researchdx_fargateCluster_ALB_test1 --tasks arn:aws:ecs:ap-northeast-1:637423646530:task/researchdx_fargateCluster_ALB_test1/50b816fea9454016b430e154b5bd513a --region ap-northeast-1 --query 'tasks[0].{TaskArn:taskArn,LastStatus:lastStatus,HealthStatus:healthStatus,StoppedReason:stoppedReason}'
{
    "TaskArn": "arn:aws:ecs:ap-northeast-1:637423646530:task/researchdx_fargateCluster_ALB_test1/50b816fea9454016b430e154b5bd513a",
    "LastStatus": "STOPPED",
    "HealthStatus": "UNKNOWN",
    "StoppedReason": "ResourceInitializationError: failed to invoke EFS utils commands to set up EFS volumes: stderr: b'mount.nfs4: access denied by server while mounting 127.0.0.1:/' Traceback (most recent call last): File \"/usr/sbin/supervisor_mount_efs\", line 52, in <module> return_code = subprocess.check_call([\"mount\", \"-t\", \"efs\", \"-o\", opts, args.fs_id_with_path, args.dir_in_container], shell=False) File \"/usr/lib64/python3.9/subprocess.py\", line 373, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['mount', '-t', 'efs', '-o', 'noresvport,tls,accesspoint=fsap-070b8abd6dc8174e2,tlsport=2999,iam,awscredsuri=/v2/credentials/7ef7d645-6c4e-40b6-b355-6c338a1b03b6', 'fs-0095aabdb7896d05c:/', '/efs-vols/EFS-volume']' returned non-zero exit status 32. During handling of the above exception, another exception occurred: Traceback (most recent call last): File \"/usr/sbin/supervisor_mount_efs\", line 56, in <module> \"message\": err.message, AttributeError: 'CalledPr: unsuccessful EFS utils comma"
}

```

app.py
```
import os
import pymysql
from flask import Flask
from datetime import datetime

app = Flask(__name__)

# RDS connection details (using environment variables)
RDS_HOST = os.environ.get('DB_HOST', 'database-1.cdmeogcuo1v2.ap-northeast-1.rds.amazonaws.com')
RDS_PORT = int(os.environ.get('DB_PORT', 3306)) 
RDS_USER = os.environ.get('DB_USER', 'admin')
RDS_PASSWORD = os.environ.get('DB_PASSWORD', 'test1password')
RDS_DB = os.environ.get('DB_NAME', 'database-1')

# EFS mount point
EFS_MOUNT_POINT = '/app'
EFS_TEST_FILE = os.path.join(EFS_MOUNT_POINT, 'efs_test_file.txt')


def test_rds_connection():
    try:
        conn = pymysql.connect(
            host=RDS_HOST,
            user=RDS_USER,
            password=RDS_PASSWORD,
            database=RDS_DB,
            port=RDS_PORT
        )
        with conn.cursor() as cursor:
            cursor.execute("SELECT 1")
            result = cursor.fetchone()
        conn.close()
        return f"RDS connection successful. Test query result: {result[0]}"
    except Exception as e:
        return f"RDS connection failed: {str(e)}"


def test_efs_connection():
    try:
        # Check if EFS is mounted
        if os.path.ismount(EFS_MOUNT_POINT):
            # Get current date and time
            current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            
            # Append new test entry
            new_content = f"EFS connection test - {current_time}\n"
            
            # Write to the file
            with open(EFS_TEST_FILE, 'a') as f:
                f.write(new_content)
            
            # Read the updated content
            with open(EFS_TEST_FILE, 'r') as f:
                full_content = f.read()
            
            return f"EFS connection successful. File content:\n{full_content}"
        else:
            return f"EFS is not mounted at {EFS_MOUNT_POINT}"
    except Exception as e:
        return f"EFS connection failed: {str(e)}"


@app.route('/')
def hello_world():
    efs_status = test_efs_connection()
    rds_status = test_rds_connection()
    return f'Hello, World!<br>EFS Status: {efs_status}<br>RDS Status: {rds_status}'


@app.route('/health')
def health_check():
    return 'OK', 200


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5001)

```

**Comment by milesAraya** [comment]
Task definition:

{
    "taskDefinitionArn": "arn:aws:ecs:ap-northeast-1:637423646530:task-definition/python_test1:12",
    "containerDefinitions": [
        {
            "name": "python_test1_container",
            "image": "637423646530.dkr.ecr.ap-northeast-1.amazonaws.com/test1:latest",
            "cpu": 256,
            "memory": 1024,
            "portMappings": [
                {
                    "containerPort": 5001,
                    "hostPort": 5001,
                    "protocol": "tcp"
                }
            ],
            "essential": true,
            "environment": [
                {
                    "name": "DB_NAME",
                    "value": "database-1"
                },
                {
                    "name": "DB_HOST",
                    "value": "your-rds-endpoint"
                },
                {
                    "name": "DB_PORT",
                    "value": "3306"
                },
                {
                    "name": "DB_USER",
                    "value": "admin"
                },
                {
                    "name": "DB_PASSWORD",
                    "value": "test1password"
                }
            ],
            "mountPoints": [
                {
                    "sourceVolume": "EFS-volume",
                    "containerPath": "/app",
                    "readOnly": false
                }
            ],
            "volumesFrom": [],
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-group": "/ecs/python_test1",
                    "awslogs-region": "ap-northeast-1",
                    "awslogs-stream-prefix": "ecs"
                }
            },
            "healthCheck": {
                "command": [
                    "CMD-SHELL",
                    "curl -f http://localhost:5001/health || exit 1"
                ],
                "interval": 30,
                "timeout": 5,
                "retries": 3,
                "startPeriod": 60
            },
            "systemControls": []
        }
    ],
    "family": "python_test1",
    "taskRoleArn": "arn:aws:iam::637423646530:role/ECSTaskRole-EFS",
    "executionRoleArn": "arn:aws:iam::637423646530:role/ecsTaskExecutionRole",
    "networkMode": "awsvpc",
    "revision": 12,
    "volumes": [
        {
            "name": "EFS-volume",
            "efsVolumeConfiguration": {
                "fileSystemId": "fs-0095aabdb7896d05c",
                "rootDirectory": "/",
                "transitEncryption": "ENABLED",
                "transitEncryptionPort": 2999,
                "authorizationConfig": {
                    "accessPointId": "fsap-070b8abd6dc8174e2",
                    "iam": "ENABLED"
                }
            }
        }
    ],
    "status": "ACTIVE",
    "requiresAttributes": [
        {
            "name": "ecs.capability.execution-role-awslogs"
        },
        {
            "name": "com.amazonaws.ecs.capability.ecr-auth"
        },
        {
            "name": "com.amazonaws.ecs.capability.task-iam-role"
        },
        {
            "name": "ecs.capability.container-health-check"
        },
        {
            "name": "ecs.capability.execution-role-ecr-pull"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
        },
        {
            "name": "ecs.capability.task-eni"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.29"
        },
        {
            "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
        },
        {
            "name": "ecs.capability.efsAuth"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
        },
        {
            "name": "ecs.capability.efs"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.25"
        }
    ],
    "placementConstraints": [],
    "compatibilities": [
        "EC2",
        "FARGATE"
    ],
    "requiresCompatibilities": [
        "FARGATE"
    ],
    "cpu": "256",
    "memory": "1024",
    "runtimePlatform": {
        "cpuArchitecture": "X86_64",
        "operatingSystemFamily": "LINUX"
    },
    "registeredAt": "2024-09-10T16:32:50.217Z",
    "registeredBy": "arn:aws:iam::637423646530:user/ecr_admin",
    "tags": []
}

**Comment by itutu-tienday** [comment]
> I cannot seem to connect EFS and ECS

- reference
  - https://dev.classmethod.jp/articles/202310-ecs-efs-01/

**Comment by milesAraya** [comment]
AWS with load balancer and logs working correctly

[PR 444](https://github.com/arayabrain/barebone-studio/pull/444/files)

![Image](https://github.com/user-attachments/assets/e60a4fe0-00c7-4325-b207-4c80ea201ccb)
