### ISSUE TITLE
Python linterのVSCode設定修正

### ISSUE THREAD

**Issue by ReiHashimoto** [arayabrain/barebone-studio#43]
- https://aka.ms/AAlgvkb
- python.linting.xxx系の設定が廃止されるため、.vscode/settings.jsonの記述を修正する
- 基本的にはextensionsを利用する運用になる
  - .vscode/extensions.jsonに推奨拡張機能は記載済

**Comment by hunghongnam** [comment]
- https://aka.ms/AAlgvkb
- Sửa đổi mô tả của .vscode/settings.json vì cài đặt python.linting.xxx sẽ bị bỏ
- Về cơ bản, nó sẽ được vận hành sử dụng extensions
   Các chức năng mở rộng được đề xuất đã mô tả trong .vscode/extensions.json

**Comment by ReiHashimoto** [comment]
- I've done in #67
