### ISSUE TITLE
[Cloud Support] OptiNiSt setup for AWS ECS environment

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/barebone-studio#439]
### Objective

- To try setting up optinist in an AWS environment using the environment setup manual
- In the course of the work, gain
  - Understand the system specifications
  - Review the configuration of the environment
  - Check and update the setup manual

- Documents
  - https://docs.google.com/spreadsheets/d/1tfZRVDXHwYbpbgWfd2FLn3E3thUvnzam/

- Related
  - #435

**Comment by milesAraya** [comment]
Please specify add more details on  
    * タスクロール: ※作成したタスクロールを指定
    * タスク実行ロール: ※作成したタスク実行ロールを指定
There are links provided, however these do not specify what 'permissions policies' are necessary. 

-----------------------

docker build -t optinist-cloud:latest -f studio/config/docker/Dockerfile.dev .
or
docker-compose -f docker-compose.dev.multiuser.yml build

-----------------------

Add row for VPC creation

-----------------------

EFS is mentioned that it is made previously, but this is then made much further down. And EFS requires VPC

Include EFS access point Root directory path
POSIX user? Root directory creation permissions?

------------------------

**Comment by milesAraya** [comment]
![Image](https://github.com/user-attachments/assets/3dc65c11-75a8-473d-965f-efff00615ec8)
