### ISSUE TITLE
Optinist Demo Env Service Auto-Stop Settings

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/barebone-studio#479]
Set up automatic service shutdown for otpinsit's AWS demo environment

- Operating Hour
  - Weekdays 9:00 - 18:00

- Target
  - ECS
  - RDS

**Comment by milesAraya** [comment]
![Image](https://github.com/user-attachments/assets/b84632f5-a688-4d70-a529-eb616887f17d)
I will check working correctly tonight
