### ISSUE TITLE
ソフトウェアバージョンアップ対応・対応ルール策定

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/barebone-studio#48]
optinistのソフトウェア・ミドルウェアのバージョンアップの実施、および実施ルールの策定
※FE、BEの両方を対象（※適宜issueを分割）

- バージョンアップ実施作業
  - FE
    - https://github.com/oist/optinist/issues/530
  - BE
    - https://github.com/oist/optinist/issues/531

- バージョンアップ実施ルールの策定
  - バージョンアップの内容（機能強化、セキュリティ情報、etc）
  - バージョンアップの頻度（年4回、etc）

**Comment by itutu-tienday** [comment]
#89 より転記

dependabotからのソフトウェアバージョンアップPRへの対応ルールを策定

- 対応スパン
- 検証内容
- レビュー体制

**Comment by ReiHashimoto** [comment]
dependabotでのバージョンアップ作業草案

https://drive.google.com/file/d/1VdBhaN3mvTHlRK5abrQ1xR4B_JjhVqtr/view?usp=drive_link

**Comment by ReiHashimoto** [comment]
FE, BEともにバージョンアップは対応済

**Comment by itutu-tienday** [comment]
@ReiHashimoto 
> dependabotでのバージョンアップ作業草案

いくつかコメントを記載します。

- dependabot の運用案については、OKだろうと思います。
  - 1点、自明かもしれませんが、アップデートの対象について記載があると良さそうかと思いました。
  - → チェック対象は FE(package.json), BE(pyproject.toml) でしょうか。
- 機能強化のアップデート方針についても、軽くまとめておくと良さそうかと思います。
  - → 掲載内容は現状は「バージョンアップ内容はgithub issuesのmilestoneで管理」「年○回程度のバージョンアップ」くらいかと思います。

**Comment by ReiHashimoto** [comment]
> 1点、自明かもしれませんが、アップデートの対象について記載があると良さそうかと思いました。
追記しました。

> 機能強化のアップデート方針についても、軽くまとめておくと良さそうかと思います
追記しました。

> またこのドキュメントは、Public掲載でOKそうかと思います。
一旦Wikiがクリーンになってから転載しようかと思います。

**Comment by itutu-tienday** [comment]
@ReiHashimoto 
ありがとうございます。

> 機能強化のアップデート方針についても、

一点、上記はoptinist本体の機能アップデートを指していました。
※例としては合わないかもしれませんが、以下のような情報のイメージ
https://ubuntu.com/about/release-cycle

**Comment by ReiHashimoto** [comment]
@itutu-tienday 
> 一点、上記はoptinist本体の機能アップデートを指していました。 ※例としては合わないかもしれませんが、以下のような情報（Roadmap）のイメージ https://ubuntu.com/about/release-cycle

なるほど、ありがとうございます。
このイメージですと、GitHubのissueに対してタグ付けなどで対応が良さそうですね。
- 対応予定の対象であるか
- どのバージョンで対応予定であるか
などが分かるようなタグ管理の運用を検討してみましょうか。
