### ISSUE TITLE
FrontEnd開発時情報表示

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/barebone-studio#71]
FrontEndの開発時（Node経由時）に、開発時用の各種情報を画面へ掲載する

- Note
  - 2段階に分けて実施予定
    1. FEの情報のみを表示
    2. BEの情報も表示（API追加必要）

- document
  - https://docs.google.com/presentation/d/1TG4OUrjIWjJCZSxMsoEjrhNb4fyQW8iI/
    - → # 71
  
- 関連
  - #70

**Comment by ReiHashimoto** [comment]
試してみたところ、nodeのversion取得が難しそうです。

サーバサイドのnodeであれば、
`process.version`などで取得できるのですが、ブラウザ向けにコンパイルするnodeの場合はこのプロパティが使えないためです。


また、devかprodかなどについては取得・表示も可能ですが、ReactDeveloperToolなどのChrome拡張機能を入れておくと判断できますので、これで間に合わす、というのもありだとは思います。

production
![Image](https://github.com/arayabrain/barebone-studio/assets/42664619/1171e45a-1539-46b9-977c-0aa2b51c2de1)

development (アイコンがオレンジ)
![Image](https://github.com/arayabrain/barebone-studio/assets/42664619/df515f96-cde3-45c7-b76e-175aa7dc1869)

**Comment by itutu-tienday** [comment]
@ReiHashimoto 
了解しました。
なお当件は、主に新規開発メンバーや 一般寄りのユーザーに対し、環境面で混乱がないようにすることを目的としていましたが（port 8000と3000で見た目が同一なため）、
ReactDeveloperTool の導入推奨はOKと思いますが、インストールドキュメントなどでTips補足しておいてもよいかもしれません。

あとは、環境情報表示があると、テスト時になど役立つケースがありそうですが、優先度は低めかと思います。

微妙に対応工数も要しそうであれば、以下でよいかと思います。
> ReactDeveloperToolなどのChrome拡張機能を入れておくと判断できますので、これで間に合わす、というのもありだとは思います。

**Comment by itutu-tienday** [comment]
必要度の面で、クローズ
