### ISSUE TITLE
テストパターン整備

### ISSUE THREAD

**Issue by ReiHashimoto** [arayabrain/barebone-studio#80]
手動での動作確認パターンを整理する

- 目的
  - テスト仕様の最新化
  - 設計ドキュメントメンテナンスのための情報整理

- タスク
  - テスト項目リスト作成
  - テスト用データの整備
  - テスト用ワークフローの整備

**Comment by itutu-tienday** [comment]
### 進捗レポート

- 進捗
  - 利用者ユースケースベースのテストケースのドラフトを作成

- NextAction
  - [ ] 現行仕様整理
    - [ ] RUNの詳細仕様の明確化
  - [ ] 画面設計資料への反映
    - #81 
    - [ ] 画面設計資料の作成ツールも検討
  - [ ] 自動テストの作成
    - #83 
    - FE
      - Workflow画面
        - [ ] RUN実行時、ノード処理にcacheが効いているかを視認できるようにする、UI改修
      - Records画面
        - [ ] 基本的なUI表示内容確認の自動テスト
      - Visualize画面
        - ※Visualize画面では、現状は、UI表示内容確認の自動テスト は省略とする
    - BE
      - [ ] RUN自動テスト
        - [ ] RUN自動テスト用の、軽量なノードの用意
