### ISSUE TITLE
ノードパラメータ表示の改善

### ISSUE THREAD

**Issue by ReiHashimoto** [arayabrain/barebone-studio#88]
- フィールド名をテキストボックススタイルからTypographyに
  - テキストボックスだと編集可能であるように見えてミスリーディングなため
- 各種データ型への適応
  - リスト型のパラメータなどが正常にリストとして処理されていない可能性が高い（stringになっている）ため、挙動の確認・修正
  - https://github.com/oist/optinist/issues/537 による仕様変更に依存する可能性がある

**Comment by hunghongnam** [comment]
Cải tiến hiển thị node parameter

- Thay đổi tên trường từ kiểu textbox sang Typography
   Bởi vì nếu là textbox thì nhìn như có thể edit nên dễ gây hiểu nhầm
- Áp dụng với các kiểu dữ liệu
  Có khả năng cao là các tham số loại list không được xử lý chính xác dưới dạng list (đang là string), vì vậy hãy check và sửa behavior
  Có khả năng phụ thuộc vào CR của task 537

**Comment by ReiHashimoto** [comment]
@hunghongnam 
> フィールド名をテキストボックススタイルからTypographyに
テキストボックスだと編集可能であるように見えてミスリーディングなため

追加の要望です。
テキストがはみ出る場合はoverflow ellipsisとし、tooltipで全体を確認できるようにしてください。

**Comment by ReiHashimoto** [comment]
UIについて、顧客に伺いをたてる。

- 現在のパラメータ名、値が横に並ぶ形式
- 以下のようにTextFieldのlabelを使用した形式
  - ![Image](https://github.com/arayabrain/barebone-studio/assets/42664619/2e813bf0-fcde-4bf3-9d82-2d61dfbcbf58)
