### ISSUE TITLE
開発規約の策定および明文化

### ISSUE THREAD

**Issue by ReiHashimoto** [arayabrain/barebone-studio#91]
開発時の設計ルールなどを策定および明文化する

- 明文化先は https://optinist.readthedocs.io/en/latest/utils/contributing.html など？

### 環境情報 
環境情報関連は、github公開情報内に記載あり（最新化必要））

- 動作対象環境
- ミドルウェア

### コーディングルール
- 参照するスタンダードなコーディングスタイル
  - ※なるべくlintツールで自動検出できるルールを考慮
- 当プロジェクト内でのルールのカスタム内容

### 実装方針
- ディレクトリ・ファイル構成に関する規定
- UI・デザイン ルール（表示、フォーム）
- ロギング・例外処理
- 非機能（セキュリティ、パフォーマンス）

### その他
- テスト（方式やカバレッジ）
- 運用（バージョン管理、デプロイ、等）

■仕様言語・フレームワーク 開発規約 参考情報
- python (pep8)
  - https://pep8-ja.readthedocs.io/ja/latest/
- javascript/typescript
  - https://maku.blog/p/avssq37/
- react
  - https://github.com/airbnb/javascript/tree/master/react
  - https://zenn.dev/meijin/articles/bulletproof-react-is-best-architecture

**Comment by itutu-tienday** [comment]
以下に反映
- #141

**Comment by itutu-tienday** [comment]
@ReiHashimoto 
基本的に、内容はGoodと思います。
いくつか、補足を記載します。

- #141 

- architecture.md
  - サポート環境（OS）の記載があるとよいと思いました。（冗長そうであればなしでもOK）
  - loggingに関して補足があるとよいと思いました。 → logging.yaml の編集で BEログのファイル記録も可能。

- pull_request.md
  - 意外と docs 中に optinistリポジトリへのリンクがないかもしれないため、リンクを貼っておいてもよいかもしれない。
    - → https://github.com/arayabrain/barebone-studio/pulls

**Comment by ReiHashimoto** [comment]
@itutu-tienday 
ありがとうございます。

> サポート環境（OS）の記載があるとよいと思いました。（冗長そうであればなしでもOK）

OSまでは一旦なしで良いかと思っています。一方で、PythonのバージョンやNode.jsのバージョンは追記しておきました。

> loggingに関して補足があるとよいと思いました。 → logging.yaml の編集で BEログのファイル記録も可能。

loggingの設定ファイルについて追記しました。

> 意外と docs 中に optinistリポジトリへのリンクがないかもしれないため、リンクを貼っておいてもよいかもしれない。

そうですね、こちら追加しました。
