### ISSUE TITLE
リリース手順の整備

### ISSUE THREAD

**Issue by ReiHashimoto** [arayabrain/barebone-studio#94]
- リリースフローの整備
  - レビュー体制
  - レビュー内容（テスト項目）
  - ブランチ管理
- 自動化可能な内容の適用
  - mainブランチへのマージをトリガーにGitHubActionsなどで自動化
    - pypiへのpush
    - dockerhubへのpush
    - readthedocsへの反映
- リリース用のmakeコマンドのメンテナンス
- リリース手順書の作成
  - #92 で作成したリポジトリで記載

- 関連
  - #91 
  - #92 
  - #95

**Comment by ReiHashimoto** [comment]
リリース手順書を作成

https://drive.google.com/file/d/1loT0dP8x-PlI_tQLxt7SMI9xSSDsa76J/view?usp=drive_link

**Comment by itutu-tienday** [comment]
@ReiHashimoto 
> リリース手順書を作成

以下へ、コメントを記載しています。 （一旦 google docs に転記してコメントしています）
https://docs.google.com/document/d/1pHzDX0lWxHKHWDC5z6RBRT4shs0z6lsuJksR-3bR_cI/

**Comment by ReiHashimoto** [comment]
@itutu-tienday 
ありがとうございます。コメントいただいた内容について、それぞれ返信させていただきました。

**Comment by itutu-tienday** [comment]
再度補足した点以外は、追加の指摘はありませんので、編集OKであれば、クローズいただければと思います。

**Comment by ReiHashimoto** [comment]
@itutu-tienday ありがとうございます。
各種指摘事項をmarkdownのファイルに反映させました。
当issueのcloseにあたり、手順書に合わせてmakeコマンドなどを修正した #152 もご確認いただければと思います。
